version: '3.8'

services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: modinstaller
            MONGO_INITDB_ROOT_PASSWORD: modinstaller
        volumes:
            - mongo-data:/data/db
        ports:
            - "27017:27017"
volumes:
    mongo-data: { }
